### ISSUE TITLE
Pinned tabs don't remain pinned after restarting Atom

### ISSUE THREAD

**Issue by michael-nischt** [ericcornelissen/pinned-tabs-for-atom#33]
Pinned tabs don't remain pinned after restarting Atom anymore. They used to but now I have to re-pin them every time I start Atom.

OS: Ubuntu 17.04
Atom: 1.17.2 x64
pinned-tabs: 1.1.0

**Comment by ericcornelissen** [comment]
I'm experiencing the same issue, but hadn't noticed it yet, thanks for reporting! I will try to solve it asap 🙂

**Comment by ericcornelissen** [comment]
Resolved this issue in 5b2385d, I will soon publish the fix 🙂

**Comment by brettz9** [comment]
This problem is still occurring for me despite having Atom 1.20.1 and pinned-tabs 2.0.1 installed.

**Comment by ericcornelissen** [comment]
That is odd 🤔 does it happen for every project/folder or just for a specific one? Also, Atom 1.20.1 or 1.22.1 (the latest version)?

**Comment by brettz9** [comment]
Re: Atom, I had been on the old version, but I updated and it is still happening. Seems to be every project/folder. And I started with a fresh window, re-adding project folders and files, but that didn't fix it for me...

**Comment by ericcornelissen** [comment]
Okay, thanks for the additional info 😄 Two more questions:
- Do you see anything in the console (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>) when you pin a tab or open a project with pinned tabs?
- Can you give a list of other community packages you're using?

**Comment by brettz9** [comment]
Thanks for the persistence with your ideas and help--by the process of elimination, I did isolate the problem to a "conflict" with [zentabs](https://atom.io/packages/zentabs), a package I had installed along with a few others including yours, and which I hadn't gotten around to really exploring.

By design, zentabs eliminates tabs when one opens more than the specified number (defaulting to 5), and that includes eliminating what *your* package considers pinned tabs too (their own notion of "pinned" tabs refers to tabs whitelisted so that they don't get auto-eliminated when there is an overflow in tab number).

However, while it seems zentabs may sometimes preserve pinned tabs ("pinned" by your usage)--apparently preexisting ones may be ok--I see problems with persisting newly pinned tabs (again, "pinned" by your usage) after a restart, even when the total tab number is less than the designated zentabs overflow number.

I don't know if this is due to the fact that both of your packages leverage "pinned" (do you perhaps have CSS classes named "pinned"?) And I didn't see any console errors, but hopefully this isolating of the problem may give you a means to resolve if you wish.

FWIW, though, it turns out I don't really need the zentabs behavior myself (I thought if your package didn't work, I could use zentabs' pinned tabs, but I hadn't looked carefully to see what their idea of "pinning" was).

**Comment by ericcornelissen** [comment]
Thank you for doing the process of elimination for me 😄 

> I don't know if this is due to the fact that both of your packages leverage "pinned" (do you perhaps have CSS classes named "pinned"?)

I do, and I expect that causes the issue

> FWIW, though, it turns out I don't really need the zentabs behavior myself

I will still look into the issue, so thanks for reporting it 😄 But for the time being you're probably better of disabling zentabs 😉 

* * *

I did open a new issue in favor of this one so it is easier for other to find out there is an issue related to zentabs, see #44
